{% set name = "minimalmodbus" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6aa3ee48e56fe54bc93405463b23bedb7f6e148fdac25308dd3822d4cf8e198d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyserial >=3

test:
  imports:
    - minimalmodbus

about:
  home: https://github.com/pyhys/minimalmodbus
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Easy-to-use Modbus RTU and Modbus ASCII implementation for Python.
  doc_url: https://minimalmodbus.readthedocs.io/
  dev_url: https://github.com/pyhys/minimalmodbus

extra:
  recipe-maintainers:
    - carlodri
