{% set name = "minimalmodbus" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3f5a56e107d537e4bb420f7e735841ab2939c8ca6fb528f5fe4124571315b64

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyserial >=3

test:
  imports:
    - minimalmodbus

about:
  home: https://github.com/pyhys/minimalmodbus
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Easy-to-use Modbus RTU and Modbus ASCII implementation for Python.
  doc_url: https://minimalmodbus.readthedocs.io/
  dev_url: https://github.com/pyhys/minimalmodbus

extra:
  recipe-maintainers:
    - carlodri
